-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 18:23:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema d02852e4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d02852e4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d02852e4` DEFAULT CHARACTER SET utf8 ;
USE `d02852e4` ;

-- -----------------------------------------------------
-- Table `d02852e4`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `password` CHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `salt` CHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d02852e4`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`login_attempts` (
  `users_id` INT NOT NULL,
  `time` VARCHAR(30) NOT NULL,
  INDEX `fk_login_attempts_users_idx` (`users_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`player` (
  `idplayer` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `level` INT NOT NULL,
  `attitude` INT NOT NULL,
  `playername` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  INDEX `fk_character_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`idplayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`world`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`world` (
  `idworld` INT NOT NULL AUTO_INCREMENT,
  `endtime` DATETIME(0) NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idworld`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`realm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`realm` (
  `idrealm` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `type` INT NULL,
  `world_idworld` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  PRIMARY KEY (`idrealm`),
  UNIQUE INDEX `idrealm_UNIQUE` (`idrealm` ASC),
  INDEX `fk_realm_world1_idx` (`world_idworld` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`army`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`army` (
  `idarmy` INT NOT NULL AUTO_INCREMENT,
  `player_idplayer` INT NOT NULL,
  PRIMARY KEY (`idarmy`),
  INDEX `fk_army_player1_idx` (`player_idplayer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`tile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`tile` (
  `idtile` INT NOT NULL AUTO_INCREMENT,
  `realm_idrealm` INT NOT NULL,
  `type` INT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  PRIMARY KEY (`idtile`),
  INDEX `fk_tile_realm1_idx` (`realm_idrealm` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`move` (
  `idmove` INT NOT NULL AUTO_INCREMENT,
  `army_idarmy` INT NOT NULL,
  `tile_idtile` INT NOT NULL,
  `tile_realm_idrealm` INT NOT NULL,
  `entertime` DATETIME(0) NOT NULL,
  INDEX `fk_army_tile_tile1_idx` (`tile_idtile` ASC, `tile_realm_idrealm` ASC),
  PRIMARY KEY (`idmove`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`unit` (
  `idunit` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `strength` INT NOT NULL,
  `player_idplayer` INT NOT NULL,
  `army_idarmy` INT NULL,
  `army_player_idplayer` INT NULL,
  PRIMARY KEY (`idunit`),
  INDEX `fk_unit_player1_idx` (`player_idplayer` ASC),
  INDEX `fk_unit_army1_idx` (`army_idarmy` ASC, `army_player_idplayer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`settlement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`settlement` (
  `tile_idtile` INT NOT NULL AUTO_INCREMENT,
  `tile_realm_idrealm` INT NOT NULL,
  `player_idplayer` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `type` INT NOT NULL DEFAULT 0,
  `population` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`tile_idtile`),
  INDEX `fk_settlement_player1_idx` (`player_idplayer` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
