-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 16:59:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema d02852e4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d02852e4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d02852e4` DEFAULT CHARACTER SET utf8 ;
USE `d02852e4` ;

-- -----------------------------------------------------
-- Table `d02852e4`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`login_attempts` (
  `users_id` INT NOT NULL,
  `time` VARCHAR(30) NOT NULL,
  INDEX `fk_login_attempts_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_login_attempts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `d02852e4`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`character` (
  `users_id` INT NOT NULL,
  `level` INT NOT NULL,
  `income` INT NOT NULL DEFAULT 1,
  `attitude` ENUM('angel', 'demon') NOT NULL,
  `idcharacter` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_character_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`idcharacter`),
  CONSTRAINT `fk_character_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `d02852e4`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`realm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`realm` (
  `idrealm` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrealm`),
  UNIQUE INDEX `idrealm_UNIQUE` (`idrealm` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`army`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`army` (
  `users_id` INT NOT NULL,
  `strength` INT NULL,
  `idarmy` INT NOT NULL,
  INDEX `fk_army_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`idarmy`, `users_id`),
  CONSTRAINT `fk_army_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `d02852e4`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`tile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`tile` (
  `idtile` INT NOT NULL,
  `realm_idrealm` INT NOT NULL,
  `type` INT NULL,
  `strength` INT NULL DEFAULT 0,
  PRIMARY KEY (`idtile`, `realm_idrealm`),
  INDEX `fk_tile_realm1_idx` (`realm_idrealm` ASC),
  CONSTRAINT `fk_tile_realm1`
    FOREIGN KEY (`realm_idrealm`)
    REFERENCES `d02852e4`.`realm` (`idrealm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d02852e4`.`army_tile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d02852e4`.`army_tile` (
  `army_idarmy` INT NOT NULL,
  `army_users_id` INT NOT NULL,
  `tile_idtile` INT NOT NULL,
  `tile_realm_idrealm` INT NOT NULL,
  PRIMARY KEY (`army_idarmy`, `army_users_id`, `tile_idtile`, `tile_realm_idrealm`),
  INDEX `fk_army_tile_tile1_idx` (`tile_idtile` ASC, `tile_realm_idrealm` ASC),
  CONSTRAINT `fk_army_tile_army1`
    FOREIGN KEY (`army_idarmy` , `army_users_id`)
    REFERENCES `d02852e4`.`army` (`idarmy` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_army_tile_tile1`
    FOREIGN KEY (`tile_idtile` , `tile_realm_idrealm`)
    REFERENCES `d02852e4`.`tile` (`idtile` , `realm_idrealm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
